<script setup>
import { computed, ref, onMounted } from 'vue'
import { RECIPE_BOOK, publishedRecipes, recipeProgress } from '../data/recipes'
import { useApi } from '../stores/api'
const q = ref(''); const category = ref('')
const api = useApi(); const serverRecipes = ref(null)
onMounted(async () => { const rows = await api.getRecipes(); if (Array.isArray(rows) && rows.length) serverRecipes.value = rows.map(r => ({ ...r, disease: r.disease || r.disease_name, recipeNumber: r.recipeNumber || r.recipe_number, originalText: r.originalText || r.original_text, sourcePageStart: r.sourcePageStart || r.source_page_start, sourcePageEnd: r.sourcePageEnd || r.source_page_end })) })
const sourceRecipes = computed(() => serverRecipes.value || publishedRecipes())
const categories = computed(() => [...new Set(sourceRecipes.value.map(r => r.category).filter(Boolean))])
const items = computed(() => { const t = q.value.trim().toLowerCase(); return sourceRecipes.value.filter(r => (!category.value || r.category === category.value) && (!t || [r.disease, r.category, r.recipeNumber, r.originalText].join(' ').toLowerCase().includes(t))) })
</script>
<template><section><h2 class="pagettl">🌿 رېتسېپلار كۈتۈپخانىسى</h2><p class="pagesub">{{ RECIPE_BOOK.title }} · {{ RECIPE_BOOK.recipes.length }} رېتسېپ</p><div class="notice">⚠️ بۇ ئەنئەنىۋى مەنبەنى ئۆگىنىش ئۈچۈندۇر؛ دوختۇر مەسلىھىتىنىڭ ئورنىنى باسمايدۇ.</div><input v-model="q" class="input" type="search" placeholder="🔍 كېسەللىك، رېتسېپ نومۇرى ياكى دورا ئىزدەش..."><select v-model="category" class="input recipe-filter"><option value="">بارلىق تۈرلەر</option><option v-for="c in categories" :key="c" :value="c">{{ c }}</option></select><div class="recipe-list"><RouterLink v-for="r in items" :key="r.id" class="recipe-card" :to="'/recipe/' + r.id"><div><b>{{ r.disease }}</b><small>{{ r.category }} · {{ r.recipeNumber }} · {{ r.sourcePageStart }}–{{ r.sourcePageEnd }}-بەت</small><p>{{ r.originalText.slice(0, 150) }}{{ r.originalText.length > 150 ? '…' : '' }}</p></div><span>{{ recipeProgress(r.id).saved ? '★' : '›' }}</span></RouterLink></div><p v-if="!items.length" class="muted">رېتسېپ تېپىلمىدى.</p></section></template>
<style scoped>.notice{padding:.8rem 1rem;margin:.8rem 0;background:#fff4d6;border:1px solid #e5c878;border-radius:var(--radius);font-size:.82rem;line-height:1.7}.recipe-filter{margin-top:.55rem}.recipe-list{display:grid;gap:10px;margin-top:1rem}.recipe-card{display:flex;justify-content:space-between;gap:12px;padding:13px 15px;background:var(--card);border:1px solid var(--line);border-radius:var(--radius);color:inherit;text-decoration:none;box-shadow:var(--shadow)}.recipe-card b,.recipe-card small{display:block}.recipe-card small{color:var(--muted);font-size:.72rem;margin-top:3px}.recipe-card p{margin:.45rem 0 0;font-size:.8rem;line-height:1.65}.recipe-card>span{font-size:1.4rem;color:var(--gold);align-self:center}</style>
