<script setup>
import { computed, ref } from 'vue'
import { publishedRecipes, recipeQuiz } from '../data/recipes'
const KEY='uytibb_recipe_srs'; const reveal=ref(false); const index=ref(0); const refresh=ref(0)
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return{}}}
function save(id,rating){const s=read();const old=s[id]||{interval:0};const interval=rating==='easy'?Math.min((old.interval||1)*2,60):rating==='hard'?1:Math.max(old.interval||1,2);s[id]={interval,nextAt:Date.now()+interval*86400000,lastRating:rating};localStorage.setItem(KEY,JSON.stringify(s));reveal.value=false;refresh.value++;if(index.value<cards.value.length-1)index.value++}
const cards=computed(()=>{refresh.value;const s=read();const now=Date.now();return publishedRecipes().filter(r=>!s[r.id]||!s[r.id].nextAt||s[r.id].nextAt<=now)})
const current=computed(()=>cards.value[index.value]); const questions=computed(()=>recipeQuiz(current.value))
</script>
<template><section><h2 class="pagettl">🧠 كۈندىلىك تەكرارلاش</h2><p class="pagesub">تەستىقلانغان رېتسېپلاردىن تەكرارلاش كارتلىرى</p><div v-if="current" class="study-card"><span class="pill green">{{ index+1 }} / {{ cards.length }}</span><h3>{{ current.disease }}</h3><p class="muted">{{ current.category }} · {{ current.recipeNumber }}-رېتسېپ</p><div v-for="item in questions" :key="item.q" class="study-question"><b>{{ item.q }}</b><button v-if="!reveal" class="btn btn-ghost btn-sm" @click="reveal=true">جاۋابنى كۆرۈش</button><p v-else>{{ item.a }}</p></div><div v-if="reveal" class="rating"><button class="btn btn-red btn-sm" @click="save(current.id,'hard')">قايتا تەكرارلايمەن</button><button class="btn btn-gold btn-sm" @click="save(current.id,'good')">ئازراق ئاسان</button><button class="btn btn-teal btn-sm" @click="save(current.id,'easy')">ئاسان</button></div></div><div v-else class="empty"><p>بۈگۈن تەكرارلايدىغان تەستىقلانغان كارتا يوق.</p><RouterLink class="btn btn-teal btn-sm" to="/recipes">رېتسېپلارنى كۆرۈش</RouterLink></div></section></template>
<style scoped>.study-card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);padding:1rem;box-shadow:var(--shadow)}.study-card h3{margin:1rem 0 .2rem}.study-question{padding:1rem 0;border-top:1px solid var(--line);line-height:1.8}.study-question button{display:block;margin-top:.5rem}.study-question p{color:var(--teal-dark);font-size:1.05rem}.rating{display:flex;gap:.4rem;flex-wrap:wrap;margin-top:1rem}</style>
