<script setup>
import { computed, ref, onMounted } from 'vue'
import { MIZAJ_BOOK } from '../../data/mizaj'
import { FARHIZ_BOOK } from '../../data/farhiz'
import { useApi } from '../../stores/api'
const KEY = 'uytibb_book_topic_reviews'; const filter = ref('needs_review'); const book = ref('all'); const selected = ref(null); const refresh = ref(0)
const api = useApi()
const remoteTopics = ref([])
onMounted(async () => { const rows = await api.getBookTopics(true); if (Array.isArray(rows)) remoteTopics.value = rows })
function read() { try { return JSON.parse(localStorage.getItem(KEY) || '{}') || {} } catch { return {} } }
function select(topic) { const state = { ...(read()[topic.id] || {}), ...(remoteTopics.value.find(item => item.topic_id === topic.id) || {}) }; selected.value = { ...topic, editedTitle: state.title || topic.title, summary: state.summary || '' } }
async function save(status) { const title = selected.value.editedTitle.trim(); const summary = selected.value.summary.trim(); const result = await api.reviewBookTopic(selected.value.id, selected.value.bookId, title, summary, status); if (result && result.status === 'error') return; const value = read(); value[selected.value.id] = { ...value[selected.value.id], status, title, summary, reviewedAt: new Date().toISOString() }; localStorage.setItem(KEY, JSON.stringify(value)); refresh.value++; selected.value = null }
const rows = computed(() => { refresh.value; const state = read(); return [MIZAJ_BOOK, FARHIZ_BOOK].flatMap(item => (item?.sections || []).map(section => { const remote = remoteTopics.value.find(topic => topic.topic_id === section.id); return { ...section, book: item.title, bookId: item.id, status: remote?.review_status || state[section.id]?.status || 'needs_review' } })).filter(row => (book.value === 'all' || row.bookId.startsWith(book.value)) && (filter.value === 'all' || row.status === filter.value)) })
</script>
<template><div class="card"><div class="card-head"><h3>📚 كىتاب بۆلەكلىرىنى تەكشۈرۈش</h3><span class="muted">{{ rows.length }} دانە</span></div><p class="acopy">OCR بۆلەكلىرىنى تەكشۈرۈپ learner نامى ۋە قىسقىچە چۈشەندۈرۈش قوشۇڭ. ئەسلى OCR تېكىستى ئۆزگەرمەيدۇ.</p><select v-model="book" class="input"><option value="all">ئىككى كىتاب</option><option value="mizaj">مىزاج</option><option value="farhiz">فەرھىز</option></select><select v-model="filter" class="input"><option value="needs_review">تەكشۈرۈش كۈتۈۋاتىدۇ</option><option value="approved">تەستىقلانغان</option><option value="rejected">رەت قىلىنغان</option><option value="all">ھەممىسى</option></select><div class="review-list"><button v-for="row in rows" :key="row.id" class="review-row" @click="select(row)"><b>{{ row.title }}</b><small>{{ row.book }} · {{ row.startPage }}–{{ row.endPage }}-بەت · {{ row.status }}</small></button></div><div v-if="selected" class="review-detail"><button class="btn btn-ghost btn-sm" @click="selected=null">×</button><h3>{{ selected.title }}</h3><p class="muted">ئەسلى مەنبە: {{ selected.startPage }}–{{ selected.endPage }}-بەت</p><label>ئۆگىنىش نامى<input v-model="selected.editedTitle" class="input"></label><label>ئۆگىنىش چۈشەندۈرۈشى<textarea v-model="selected.summary" class="input" rows="4" placeholder="مۇتەخەسسىس تەستىقلىغان قىسقىچە چۈشەندۈرۈش..."></textarea></label><details><summary>ئەسلى OCR تېكىستىنى كۆرۈش</summary><article>{{ selected.text }}</article></details><div class="review-actions"><button class="btn btn-teal" @click="save('approved')">ساقلاش ۋە تەستىقلاش</button><button class="btn btn-red" @click="save('rejected')">رەت قىلىش</button><button class="btn btn-ghost" @click="save('needs_review')">لايىھە سۈپىتىدە ساقلاش</button></div></div></div></template>
<style scoped>.acopy{line-height:1.7;color:var(--muted)}.input{margin:.3rem 0}.review-list{display:grid;gap:.4rem;margin-top:.7rem}.review-row{display:grid;gap:.2rem;text-align:start;padding:.7rem;border:1px solid var(--line);background:var(--card);color:inherit;cursor:pointer}.review-row small{color:var(--muted)}.review-detail{margin-top:1rem;padding:1rem;border-top:2px solid var(--teal)}.review-detail label{display:block;margin:.6rem 0}.review-detail article{white-space:pre-wrap;line-height:1.9;max-height:35rem;overflow:auto}.review-actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1rem}</style>
