<script setup>
import { computed, ref } from 'vue'
import { MIZAJ_BOOK } from '../../data/mizaj'
import { FARHIZ_BOOK } from '../../data/farhiz'
const KEY = 'uytibb_book_topic_reviews'; const refresh = ref(0); const filter = ref('needs_review'); const book = ref('all'); const selected = ref(null)
function read() { try { return JSON.parse(localStorage.getItem(KEY) || '{}') || {} } catch { return {} } }
function setStatus(topic, status) { const value = read(); value[topic.id] = { status, reviewedAt: new Date().toISOString() }; localStorage.setItem(KEY, JSON.stringify(value)); refresh.value++ }
const rows = computed(() => { refresh.value; const state = read(); return [MIZAJ_BOOK, FARHIZ_BOOK].flatMap(item => (item?.sections || []).map(section => ({ ...section, book: item.title, bookId: item.id, status: state[section.id]?.status || 'needs_review' }))).filter(row => (book.value === 'all' || row.bookId.startsWith(book.value)) && (filter.value === 'all' || row.status === filter.value)) })
</script>
<template><div class="card"><div class="card-head"><h3>📚 كىتاب بۆلەكلىرىنى تەكشۈرۈش</h3><span class="muted">{{ rows.length }} دانە</span></div><p class="acopy">OCR دىن چىققان بۆلەك نامى، بەت دائىرىسى ۋە تولۇق تېكىستىنى تەكشۈرۈڭ. تەستىق بۇ يەرلىك ئوبزور ھالىتى؛ مەنبە JSON ھەرگىز ئۆزگەرمەيدۇ.</p><select v-model="book" class="input"><option value="all">ئىككى كىتاب</option><option value="mizaj">مىزاج</option><option value="farhiz">فەرھىز</option></select><select v-model="filter" class="input"><option value="needs_review">تەكشۈرۈش كۈتۈۋاتىدۇ</option><option value="approved">تەستىقلانغان</option><option value="rejected">رەت قىلىنغان</option><option value="all">ھەممىسى</option></select><div class="review-list"><button v-for="row in rows" :key="row.id" class="review-row" @click="selected=row"><b>{{ row.title }}</b><small>{{ row.book }} · {{ row.startPage }}–{{ row.endPage }}-بەت · {{ row.status }}</small></button></div><div v-if="selected" class="review-detail"><button class="btn btn-ghost btn-sm" @click="selected=null">×</button><h3>{{ selected.title }}</h3><p class="muted">{{ selected.startPage }}–{{ selected.endPage }}-بەت</p><article>{{ selected.text }}</article><div class="review-actions"><button class="btn btn-teal" @click="setStatus(selected,'approved')">تەستىقلاش</button><button class="btn btn-red" @click="setStatus(selected,'rejected')">رەت قىلىش</button></div></div></div></template>
<style scoped>.acopy{line-height:1.7;color:var(--muted)}.input{margin:.3rem 0}.review-list{display:grid;gap:.4rem;margin-top:.7rem}.review-row{display:grid;gap:.2rem;text-align:start;padding:.7rem;border:1px solid var(--line);background:var(--card);color:inherit;cursor:pointer}.review-row small{color:var(--muted)}.review-detail{margin-top:1rem;padding:1rem;border-top:2px solid var(--teal)}.review-detail article{white-space:pre-wrap;line-height:1.9;max-height:35rem;overflow:auto}.review-actions{display:flex;gap:.5rem;margin-top:1rem}</style>
