<script setup>
import { computed, ref } from 'vue'
import { useApi } from '../../stores/api'
const api=useApi()
const books=Object.values(import.meta.glob('../../data/herbData-*.js',{eager:true,import:'HERB_BOOK'}));const herbs=books.flatMap(b=>b?.herbs||[]);const q=ref('');const refresh=ref(0);const key='uytibb_herb_review_overrides';const historyHerb=ref(null);const history=ref([])
function read(){try{return JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{return{}}}async function save(id,status,safetyStatus=status==='approved'?'reviewed':status==='rejected'?'blocked':'unreviewed'){const note=prompt('تەكشۈرۈش خاتىرىسى (ئىختىيارى):')||'';const remote=await api.reviewHerb(id,status,safetyStatus,note);if(remote&&remote.status==='ok'){const o=read();o[id]={reviewStatus:status,safetyStatus};localStorage.setItem(key,JSON.stringify(o));refresh.value++}}async function showHistory(h){historyHerb.value=h;history.value=await api.getHerbHistory(h.id)}function status(h){return read()[h.id]?.reviewStatus||h.reviewStatus||'needs_review'}
const rows=computed(()=>{refresh.value;const t=q.value.trim().toLowerCase();return herbs.filter(h=>!t||[h.name,h.latinName,h.originalText].join(' ').toLowerCase().includes(t))})
</script>
<template><div class="card"><h3>🌱 خام دورىلارنى تەكشۈرۈش</h3><p class="acopy">خام دورا كىتابلىرىدىكى نام، لاتىنچە ئىسىم ۋە ئاگاھلاندۇرۇشلار مۇتەخەسسىس تەستىقىدىن ئۆتكەندىن كېيىنلا ئىشلىتىلىدۇ.</p><input v-model="q" class="input" type="search" placeholder="خام دورا ئىزدەش..."><p class="muted">{{rows.length}} دانە · مەنبەدىكى ھەممە خاتىرە دەسلەپتە تەكشۈرۈشكە موھتاج</p><div v-for="h in rows" :key="h.id" class="herb-row"><div><b>{{h.name}}</b><small>{{h.latinName||'لاتىنچە نام يوق'}} · {{h.sourcePageStart||'—'}}-بەت</small><p>{{(h.originalText||'').slice(0,180)}}</p></div><span class="tbadge">{{status(h)}}</span><div class="qa-row"><button class="btn btn-teal btn-sm" @click="save(h.id,'approved')">تەستىقلاش</button><button class="btn btn-red btn-sm" @click="save(h.id,'rejected')">رەت قىلىش</button><button class="btn btn-ghost btn-sm" @click="save(h.id,'needs_review')">قايتا تەكشۈرۈش</button><button class="btn btn-ghost btn-sm" @click="showHistory(h)">تارىخ</button></div></div><p v-if="!rows.length" class="muted">تېخى خام دورا كىتابى ئىمپورت قىلىنمىدى.</p><div v-if="historyHerb" class="history-panel"><button class="btn btn-ghost btn-sm" @click="historyHerb=null">×</button><b>{{historyHerb.name}} · review history</b><p v-if="!history.length" class="muted">تارىخ يوق.</p><div v-for="item in history" :key="item.id" class="history-row"><div>{{item.review_status}} · {{item.reviewer||'admin'}} · {{item.created_at}}</div><small v-if="item.note">📝 {{item.note}}</small></div></div></div></template>
<style scoped>.herb-row{display:grid;grid-template-columns:1fr auto;gap:.4rem 1rem;padding:.8rem 0;border-top:1px solid var(--line)}.herb-row small{display:block;color:var(--muted);margin-top:.2rem}.herb-row p{margin:.4rem 0;white-space:pre-wrap;font-size:.8rem;line-height:1.6}.herb-row .qa-row{grid-column:1/-1}</style>
