<script setup>
import { computed, ref } from 'vue'
import { RECIPE_BOOK } from '../../data/recipes'
import { useApi } from '../../stores/api'
const api=useApi();const key='uytibb_recipe_editor_overrides';const q=ref('');const filter=ref('all');const page=ref(1);const refresh=ref(0);const pageSize=25;const historyRecipe=ref(null);const history=ref([]);const historyLoading=ref(false)
function read(){try{return JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{return{}}}function write(v){localStorage.setItem(key,JSON.stringify(v));refresh.value++}function effective(r){return {...r,...(read()[r.id]||{})}}
const matching=computed(()=>{refresh.value;const t=q.value.trim().toLowerCase();return RECIPE_BOOK.recipes.filter(r=>{const x=effective(r);return(filter.value==='all'||x.reviewStatus===filter.value)&&(!t||[r.disease,r.recipeNumber,r.originalText].join(' ').toLowerCase().includes(t))})});const rows=computed(()=>matching.value.slice((page.value-1)*pageSize,page.value*pageSize));const pageCount=computed(()=>Math.max(1,Math.ceil(matching.value.length/pageSize)))
const summary=computed(()=>{refresh.value;const a=RECIPE_BOOK.recipes.map(effective),s=n=>a.filter(r=>r.reviewStatus===n).length,z=n=>a.filter(r=>r.safetyStatus===n).length;return{total:a.length,pending:s('needs_review'),approved:s('approved'),rejected:s('rejected'),unsafe:z('unreviewed'),ingredients:a.filter(r=>(r.ingredients||[]).length).length,categories:new Set(a.map(r=>r.category).filter(Boolean)).size}})
function resetPage(){page.value=1}async function setStatus(r,reviewStatus,safetyStatus){const remote=await api.reviewRecipe(r.id,reviewStatus,safetyStatus);if(remote&&remote.status==='ok'){r.reviewStatus=reviewStatus;r.safetyStatus=safetyStatus}const o=read();o[r.id]={...(o[r.id]||{}),reviewStatus,safetyStatus};write(o)}async function openHistory(r){historyRecipe.value=r;historyLoading.value=true;history.value=await api.getRecipeHistory(r.id);historyLoading.value=false}
</script>
<template><div><div class="card"><h3>🌿 رېتسېپ تەكشۈرۈش</h3><p class="acopy">OCR رېتسېپلىرى ئاممىغا چىقىرىلىشتىن بۇرۇن مەزمۇن ۋە بىخەتەرلىك جەھەتتىن مۇتەخەسسىس تەرىپىدىن تەكشۈرۈلسۇن.</p><div class="summary-grid"><span>جەمئىي <b>{{summary.total}}</b></span><span>تەكشۈرۈلمىگەن <b>{{summary.pending}}</b></span><span>تەستىقلانغان <b>{{summary.approved}}</b></span><span>بىخەتەرلىك كۈتۈۋاتقان <b>{{summary.unsafe}}</b></span><span>تەركىب بار <b>{{summary.ingredients}}</b></span><span>تۈر <b>{{summary.categories}}</b></span></div><input v-model="q" @input="resetPage" class="input" type="search" placeholder="كېسەللىك ياكى رېتسېپ ئىزدەش..."><select v-model="filter" @change="resetPage" class="input"><option value="all">ھەممىسى</option><option value="needs_review">تەكشۈرۈلمىگەن</option><option value="approved">تەستىقلانغان</option><option value="rejected">رەت قىلىنغان</option></select><small class="muted">{{matching.length}} دانە · {{page}}/{{pageCount}} بەت</small></div><div class="recipe-review-list"><div v-for="r in rows" :key="r.id" class="card"><b>{{r.disease}} · {{r.recipeNumber}}</b><small>{{r.sourcePageStart}}–{{r.sourcePageEnd}}-بەت</small><p class="review-text">{{r.originalText.slice(0,260)}}{{r.originalText.length>260?'…':''}}</p><div class="qa-row"><button class="btn btn-ghost btn-sm" @click="setStatus(r,'approved','unreviewed')">مەزمۇن تەستىقلاش</button><button class="btn btn-ghost btn-sm" @click="setStatus(r,'needs_review','reviewed')">بىخەتەرلىك تەستىقلاش</button><button class="btn btn-teal btn-sm" @click="setStatus(r,'approved','reviewed')">✓ تولۇق publish</button><button class="btn btn-red btn-sm" @click="setStatus(r,'rejected','blocked')">✕ رەت قىلىش</button><button class="btn btn-ghost btn-sm" @click="openHistory(r)">تارىخ</button></div></div></div><div class="qa-row pager"><button class="btn btn-ghost btn-sm" :disabled="page<=1" @click="page--">‹ ئالدىنقى</button><button class="btn btn-ghost btn-sm" :disabled="page>=pageCount" @click="page++">كېيىنكى ›</button></div><div v-if="historyRecipe" class="history-panel card"><button class="btn btn-ghost btn-sm" @click="historyRecipe=null">×</button><h3>تەكشۈرۈش تارىخى · {{historyRecipe.recipeNumber}}</h3><p v-if="historyLoading" class="muted">Loading…</p><p v-else-if="!history.length" class="muted">تارىخ يوق.</p><div v-for="item in history" v-else :key="item.id" class="history-row"><b>{{item.review_status}} / {{item.safety_status}}</b><span>{{item.reviewer||'admin'}} · {{item.created_at}}</span></div></div></div></template>
<style scoped>.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:.8rem 0}.summary-grid span{padding:.55rem;background:var(--card-2);border-radius:var(--radius-sm);font-size:.72rem}.summary-grid b{display:block;font-size:1.1rem;color:var(--teal)}.recipe-review-list{display:grid;gap:10px;margin-top:10px}.recipe-review-list small{display:block;color:var(--muted);margin-top:4px}.review-text{white-space:pre-wrap;line-height:1.7;font-size:.82rem}.recipe-review-list .card{margin:0}.history-panel{position:fixed;inset:auto 1rem 1rem;z-index:10;box-shadow:0 8px 30px #0003}.history-row{display:flex;justify-content:space-between;gap:1rem;padding:.55rem 0;border-top:1px solid var(--line);font-size:.8rem}.history-row span{color:var(--muted)}</style>
