<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { MIZAJ_BOOK, mizajSections } from '../data/mizaj'
import { FARHIZ_BOOK, farhizSections } from '../data/farhiz'
import { markTopicStudied, toggleTopicSaved, topicProgress } from '../data/topicProgress'
import { topicReviewStatus } from '../data/topicReview'
import { useApi } from '../stores/api'
const route = useRoute(); const api = useApi(); const q = ref(''); const topicQ = ref(''); const selected = ref(null); const remote = ref([])
const isFarhiz = computed(() => route.path.startsWith('/farhiz')); const book = computed(() => isFarhiz.value ? FARHIZ_BOOK : MIZAJ_BOOK)
const baseSections = computed(() => isFarhiz.value ? farhizSections() : mizajSections())
const sections = computed(() => baseSections.value.filter(s => remote.value.find(r => r.topic_id === s.id)?.review_status !== 'rejected').map(s => { const r = remote.value.find(item => item.topic_id === s.id); return r ? { ...s, title: r.title || s.title, summary: r.summary || s.summary || '' } : s }))
const visibleSections = computed(() => sections.value.filter(s => !topicQ.value.trim() || s.title.toLocaleLowerCase().includes(topicQ.value.trim().toLocaleLowerCase())))
const pages = computed(() => (book.value?.pages || []).filter(p => !q.value.trim() || p.text.toLocaleLowerCase().includes(q.value.trim().toLocaleLowerCase())))
const state = computed(() => selected.value ? topicProgress(selected.value.id) : {})
const index = computed(() => sections.value.findIndex(s => s.id === selected.value?.id))
function openSection(s) { selected.value = s; requestAnimationFrame(() => document.querySelector('.topic-reader')?.scrollIntoView({ behavior: 'smooth', block: 'start' })) }
function move(delta) { const next = sections.value[index.value + delta]; if (next) openSection(next) }
function save() { toggleTopicSaved(selected.value.id); selected.value = { ...selected.value } }
function studied() { markTopicStudied(selected.value.id); selected.value = { ...selected.value } }
onMounted(async () => { const rows = await api.getBookTopics(); if (Array.isArray(rows)) remote.value = rows.filter(r => r.book_id === book.value?.id); const target = sections.value.find(s => s.id === route.query.section); if (target) openSection(target) })
</script>
<template><section v-if="book"><RouterLink to="/books" class="back">‹ كىتابلارغا قايتىش</RouterLink><h2 class="pagettl">{{ isFarhiz ? '📘' : '🧭' }} {{ book.title }}</h2><p class="pagesub">{{ book.subtitle }} · {{ book.pages.length }} بەت · {{ sections.length }} بۆلەك</p><div class="notice">⚠️ بۇ مەنبە ئۆگىنىش ئۈچۈندۇر؛ كېسەللىك ياكى داۋالاش قارارىنى مۇتەخەسسىس بىلەن لاياقەتلىك دوختۇر بىلەن مەسلىھەتلىشىڭ.</div><input v-model="topicQ" class="input" type="search" placeholder="بۆلەك نامىدىن ئىزدەش..." aria-label="بۆلەك نامىدىن ئىزدەش"><div v-if="selected" class="topic-reader reader card"><div class="reader-head"><div><h3>{{ selected.title }}</h3><small>{{ selected.startPage }}–{{ selected.endPage }}-بەت · {{ topicReviewStatus(selected.id) === 'approved' ? '✅ تەكشۈرۈلگەن' : '📝 OCR لايىھە' }}</small></div><button class="btn btn-ghost btn-sm" @click="selected=null">×</button></div><div v-if="selected.summary" class="summary"><b>🧠 ئۆگىنىش چۈشەندۈرۈشى</b><p>{{ selected.summary }}</p></div><article><div v-for="page in selected.sourcePages" :key="page.pageNumber" class="source-page"><h4>{{ page.displayPageNumber }}-بەت</h4><p>{{ page.text || 'بوش بەت' }}</p></div></article><div class="reader-actions"><button class="btn btn-teal" @click="save">{{ state.saved ? '★ ساقلانغان' : '☆ ساقلاش' }}</button><button class="btn btn-ghost" @click="studied">{{ state.studied ? '✓ ئۆگىنىلدى' : 'ئۆگىنىلدى دەپ بەلگىلەش' }}</button><RouterLink class="btn btn-ghost" :to="(isFarhiz ? '/farhiz' : '/mizaj') + '/quiz?section=' + selected.id">📝 quiz</RouterLink></div><div class="section-nav"><button class="btn btn-ghost" :disabled="index<=0" @click="move(-1)">‹ ئالدىنقى بۆلەك</button><button class="btn btn-ghost" :disabled="index>=sections.length-1" @click="move(1)">كېيىنكى بۆلەك ›</button></div></div><div class="toc card"><b>بۆلەك يولباشچىسى ({{ visibleSections.length }})</b><button v-for="s in visibleSections" :key="s.id" :class="'level-' + s.level" @click="openSection(s)">{{ s.title }} <small>{{ s.startPage }}–{{ s.endPage }}-بەت</small></button></div><div v-if="!selected && q" class="page-list"><button v-for="page in pages" :key="page.pageNumber" class="card page-row" @click="openSection(sections.find(s => s.startPage === page.pageNumber) || { id: 'page-' + page.pageNumber, title: page.displayPageNumber + '-بەت', startPage: page.pageNumber, endPage: page.pageNumber, sourcePages: [page] })"><b>{{ page.displayPageNumber }}-بەت</b><span>{{ page.text.slice(0,220) }}…</span></button></div><input v-model="q" class="input page-search" type="search" placeholder="ئەسلى OCR بەتلىرىدىن ئىزدەش..."></section><section v-else><h2 class="pagettl">كىتاب تېپىلمىدى</h2></section></template>
<style scoped>.back{display:inline-block;margin-bottom:.7rem;color:var(--accent-ink)}.notice,.summary{padding:.8rem 1rem;margin:.8rem 0;background:#fff4d6;border:1px solid #e5c878;border-radius:var(--radius);line-height:1.8}.summary{background:var(--card-2);border-color:var(--line)}.toc{display:grid;gap:.4rem;margin-top:1rem;padding:1rem}.toc button{border:0;background:transparent;text-align:start;color:inherit;cursor:pointer;padding:.35rem}.toc button.level-2{font-weight:800;margin-top:.35rem}.toc button.level-3{padding-inline-start:1.2rem;color:var(--muted)}.toc small{float:inline-end;color:var(--muted)}.reader{margin-top:1rem;scroll-margin-top:1rem}.reader-head{display:flex;justify-content:space-between;align-items:center}.reader article{line-height:2}.source-page{border-top:1px solid var(--line);padding-top:.7rem;margin-top:.8rem}.source-page h4{color:var(--teal);margin:0}.source-page p{white-space:pre-wrap}.reader-actions,.section-nav{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}.page-search{margin-top:1rem}.page-list{display:grid;gap:.5rem;margin-top:1rem}.page-row{text-align:start;color:inherit;cursor:pointer;border:1px solid var(--line)}</style>
